### ISSUE TITLE
Update dry-rb gems

### ISSUE THREAD

**Issue by k0va1** [iarie/pwush#2]
Hi! Firstly I would like to say thank you for this gem. But when I digging into sources I found some deprecated methods like `constructor-types`. https://github.com/iarie/pwush/blob/master/lib/pwush/message.rb

https://dry-rb.org/gems/dry-struct/constructor-types/

**Comment by iarie** [comment]
Yeah, @hetsketch, I wanted to do this month ago, looks like time has come

**Comment by k0va1** [comment]
@iarie thanks! One more question: are you using gem in prod? Is everything fine?

**Comment by iarie** [comment]
@hetsketch a bit late, sorry I missed your answer, we use it in production for our messaging service and all seems fine!
